package com.binayak.java8.stream;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;

public class MapAndFlatMap {
    public static void main(String[] args) {
        //*******************Example-1:*******************************
        //use of map()
        List<String> words = Arrays.asList("Java", "8", "Streams");
        List<Integer> lengths = words.stream()
                .map(String::length)
                .collect(Collectors.toList());
        //Result: [4, 1, 7]

        // use of flatMap()
        List<List<String>> nestedList = Arrays.asList(
                Arrays.asList("Laptop", "Phone"),
                Arrays.asList("Mouse", "Keyboard")
        );

        List<String> flatList = nestedList.stream()
                .flatMap(Collection::stream)
                .collect(Collectors.toList());
        //Result: [Laptop, Phone, Mouse, Keyboard]

        //************************Example-2:**********************************

        // Use of map()

        // making the array list object
        List<String> fruit = new ArrayList<>();
        fruit.add("Apple");
        fruit.add("mango");
        fruit.add("pineapple");
        fruit.add("kiwi");
        System.out.println("List of fruit-" + fruit);
        // lets use map() to convert list of fruit
        List<Integer> list = fruit.stream()
                .map(s -> s.length())
                .collect(Collectors.toList());
        System.out.println("List generated by map-" + list);

        // use of flatMap()

        // making the arraylist object of List of Integer
        List<List<Integer>> number = new ArrayList<>();

        // adding the elements to number arraylist
        number.add(Arrays.asList(1, 2));
        number.add(Arrays.asList(3, 4));
        number.add(Arrays.asList(5, 6));
        number.add(Arrays.asList(7, 8));

        System.out.println("List of list-" + number);

        // using flatmap() to flatten this list
        List<Integer> flatList2
                = number.stream()
                .flatMap(list2 -> list2.stream())
                .collect(Collectors.toList());
        // printing the list
        System.out.println("List generate by flatMap-"
                + flatList2);
    }
};
